name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - run: echo NODE_VERSION=$(jq -r .volta.node package.json) >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_ACCESS_TOKEN }}
      - run: npm run lint
      - run: npm run build
      - run: npm test

